name: Build and Deploy EC2

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
      - run: npm ci --force
      - run: npm build --force

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ec2-18-223-39-160.us-east-2.compute.amazonaws.com
          REMOTE_USER: ubuntu
          TARGET: client/
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_AFTER: |
            cd client
            touch .env.local
            echo "${{ secrets.PROD_ENV_FILE }}" > .env.local
            pm2 restart npm -- start
            echo $RSYNC_STDOUT
      
