name: Build and Deploy EC2

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    
   
    - name: Build & Deploy
      env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ec2-18-223-39-160.us-east-2.compute.amazonaws.com
            USER_NAME: ubuntu
      
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v18.16.0/bin

              # Now we have got the access of EC2 and we will start the deploy.
              
              cd client &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
              npm ci --force
              npm run build --force &&
              touch .env.local &&
              echo "${{ secrets.PROD_ENV_FILE }}" > .env.local &&
              pm2 start npm -- start --update-env
              '
